# .github/workflows/deploy.yml
name: Django CI/CD

on:
  push:
    branches:
      - develope
      - feature/home_work

jobs:
  test-and-deploy:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:15
        env:
          POSTGRES_DB: ${{ secrets.DB_NAME }}  # Из .env
          POSTGRES_USER: ${{ secrets.DB_USER }}  # Из .env
          POSTGRES_PASSWORD: ${{ secrets.DB_PASSWORD }}  # Из .env
        ports:
          - 5432:5432
        options: >-
          --health-cmd="pg_isready -U ${secrets.DB_USER} -d ${secrets.DB_NAME}"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=10

      redis:
        image: redis:7
        ports:
          - 6379:6379
        options: >-
          --health-cmd="redis-cli ping"
          --health-interval=5s
          --health-timeout=2s
          --health-retries=5

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m venv .venv
          . .venv/bin/activate
          pip install --upgrade pip
          pip install -r ./requirements.txt

      - name: Wait for PostgreSQL
        run: |
          for i in {1..30}; do
            pg_isready -h postgres -p 5432 -U ${secrets.DB_USER} -d ${secrets.DB_NAME} && break
            echo "Waiting for PostgreSQL... ($i)"
            sleep 5
          done

      - name: Wait for Redis
        run: |
          for i in {1..10}; do
            redis-cli -h redis -p 6379 ping && break
            echo "Waiting for Redis... ($i)"
            sleep 2
          done

      - name: Run tests
        env:
          SECRET_KEY: ${{ secrets.SECRET_KEY }}
          DEBUG: 1
          ALLOWED_HOSTS: 127.0.0.1,localhost
          DJANGO_SETTINGS_MODULE: home_work_7.settings
          DB_NAME: ${{ secrets.DB_NAME }}
          DB_USER: ${{ secrets.DB_USER }}
          DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
          DB_HOST: postgres  # Имя сервиса
          DB_PORT: 5432
          REDIS_HOST: redis  # Имя сервиса
          REDIS_PORT: 6379
          STRIPE_API_KEY: ${{ secrets.STRIPE_API_KEY }}
        run: |
          . .venv/bin/activate
          cd backend
          python manage.py test

      - name: Deploy to server
        if: success()
        uses: appleboy/ssh-action@v0.1.9
        with:
          host: ${{ secrets.SERVER_IP }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          port: ${{ secrets.SSH_PORT }}
          script: |
            cd ~/Home_Work_10
            git reset --hard
            git pull origin feature/home_work
            docker-compose down
            docker-compose up -d --build
