name: Django CI/CD

on:
  push:
    branches:
      - develope
      - feature/home_work

jobs:
  test-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install tools
        run: |
          sudo apt-get update
          sudo apt-get install -y postgresql-client redis-tools docker.io

      #######################
      #  START POSTGRES
      #######################
      - name: Start PostgreSQL using secrets
        run: |
          docker run -d \
            --name pg \
            -e POSTGRES_DB=${{ secrets.POSTGRES_DB }} \
            -e POSTGRES_USER=${{ secrets.POSTGRES_USER }} \
            -e POSTGRES_PASSWORD=${{ secrets.POSTGRES_PASSWORD }} \
            -p 5432:5432 \
            postgres:15

      - name: Wait for PostgreSQL
        run: |
          for i in {1..20}; do
            pg_isready -h localhost -U ${{ secrets.POSTGRES_USER }} && break
            echo "Waiting for PostgreSQL..."
            sleep 3
          done

      #######################
      #  START REDIS
      #######################
      - name: Start Redis
        run: |
          docker run -d \
            --name redis \
            -p 6379:6379 \
            redis:7

      - name: Wait for Redis
        run: |
          for i in {1..10}; do
            redis-cli ping && break
            echo "Waiting for Redis..."
            sleep 2
          done

      #######################
      #  Python & tests
      #######################
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          python -m venv .venv
          . .venv/bin/activate
          pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run tests
        env:
          SECRET_KEY: ${{ secrets.SECRET_KEY }}
          DEBUG: 1
          DJANGO_SETTINGS_MODULE: home_work_7.settings

          DB_NAME: ${{ secrets.POSTGRES_DB }}
          DB_USER: ${{ secrets.POSTGRES_USER }}
          DB_PASSWORD: ${{ secrets.POSTGRES_PASSWORD }}
          DB_HOST: localhost
          DB_PORT: 5432

          REDIS_HOST: localhost
          REDIS_PORT: 6379

          STRIPE_API_KEY: ${{ secrets.STRIPE_API_KEY }}

        run: |
          . .venv/bin/activate
          python manage.py test

      #######################
      #  Deploy
      #######################
      - name: Deploy to server
        if: success()
        uses: appleboy/ssh-action@v0.1.9
        with:
          host: ${{ secrets.SERVER_IP }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          port: ${{ secrets.SSH_PORT }}
          script: |
            cd ~/Home_Work_10
            git reset --hard
            git pull origin feature/home_work
            docker-compose down
            docker-compose up -d --build
